plugins:
  - semantic-release-gitmoji
  - "@semantic-release/github"
  - - "@semantic-release/npm"
    - pkgRoot: Packages/com.nekometer.esnya/esnya-unity-tools
      npmPublish: false
  - "@semantic-release/git"
