name: Release Unity Package

on:
  - push

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{steps.package_name.outputs.package_name}}
    steps:
      - id: package_name
        #run: echo "::set-output name=package_name::$(echo ${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/})"
        run: echo "::set-output name=package_name::$(echo ${GITHUB_REPOSITORY##*/})"

  release:
    needs: prebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{runner.os}}-node_modules
      - name: Install dependencies
        run: npm install semantic-release @semantic-release/github @semantic-release/exec semantic-release-gitmoji @semantic-release/npm @semantic-release/git

      - run: |
          find Assets -name \*.meta > metaList
          mkdir dist
          cat metaList
      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'dist/${{needs.prebuild.outputs.package_name}}.unitypackage'
          include-files: metaList

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
